			<div class="slider-revolution">
				<div id="slider-revolution">
					<ul>
						<li data-transition="cube">
							<img src="{{ asset('assets/pic/slideshow/item-4.jpg') }}" alt="">
							<div class="tp-caption title skewfromrightshort tp-resizeme rs-parallaxlevel-0"
								data-x="center"
								data-hoffset="80"
								data-y="center"
								data-speed="500"
								data-start="500"
								data-easing="Power3.easeInOut"
								data-splitin="chars"
								data-splitout="none"
								data-elementdelay="0.1"
								data-endelementdelay="0.1"
								style="z-index: 1; max-width: auto; max-height: auto; white-space: nowrap;">Realiza Tu Pago Puntual
							</div>
							<div class="tp-caption sft tp-resizeme rs-parallaxlevel-0"
								data-x="center"
								data-hoffset="-215"
								data-y="center" 
								data-voffset="-96"
								data-customin="x:0;y:0;z:0;rotationX:0;rotationY:0;rotationZ:0;scaleX:0;scaleY:0;skewX:0;skewY:0;opacity:0;transformPerspective:600;transformOrigin:50% 50%;"
								data-speed="500"
								data-start="3000"
								data-easing="Power3.easeInOut"
								data-splitin="none"
								data-splitout="none"
								data-elementdelay="0.1"
								data-endelementdelay="0.1"
								data-linktoslide="next"
								style="z-index: 1; max-width: auto; max-height: auto; white-space: nowrap;"><i class="fa fa-tint"></i>
							</div>
							<div class="tp-caption sfl tp-resizeme rs-parallaxlevel-0"
								data-x="center"
								data-hoffset="-300"
								data-y="center" 
								data-customin="x:0;y:0;z:0;rotationX:0;rotationY:0;rotationZ:0;scaleX:0;scaleY:0;skewX:0;skewY:0;opacity:0;transformPerspective:600;transformOrigin:50% 50%;"
								data-speed="500"
								data-start="3300"
								data-easing="Power3.easeInOut"
								data-splitin="none"
								data-splitout="none"
								data-elementdelay="0.1"
								data-endelementdelay="0.1"
								data-linktoslide="next"
								style="z-index: 1; max-width: auto; max-height: auto; white-space: nowrap;"><i class="fa fa-2 fa-university"></i>
							</div>
							<div class="tp-caption sfb tp-resizeme rs-parallaxlevel-0"
								data-x="center"
								data-hoffset="-215"
								data-y="center" 
								data-voffset="96"
								data-customin="x:0;y:0;z:0;rotationX:0;rotationY:0;rotationZ:0;scaleX:0;scaleY:0;skewX:0;skewY:0;opacity:0;transformPerspective:600;transformOrigin:50% 50%;"
								data-speed="500"
								data-start="3600"
								data-easing="Power3.easeInOut"
								data-splitin="none"
								data-splitout="none"
								data-elementdelay="0.1"
								data-endelementdelay="0.1"
								data-linktoslide="next"
								style="z-index: 1; max-width: auto; max-height: auto; white-space: nowrap;"><i class="fa fa-3 fa-smile-o"></i>
							</div>
							<div class="tp-caption sfb tp-resizeme rs-parallaxlevel-0"
								data-x="center"
								data-hoffset="265"
								data-y="center" 
								data-voffset="91"
								data-customin="x:0;y:0;z:0;rotationX:0;rotationY:0;rotationZ:0;scaleX:0;scaleY:0;skewX:0;skewY:0;opacity:0;transformPerspective:600;transformOrigin:50% 50%;"
								data-speed="500"
								data-start="4000"
								data-easing="Power3.easeInOut"
								data-splitin="none"
								data-splitout="none"
								data-elementdelay="0.1"
								data-endelementdelay="0.1"
								data-linktoslide="next"
								style="z-index: 1; max-width: auto; max-height: auto; white-space: nowrap;"><a href="#" class="button-my">Hidrosistema de Córdoba</a>
							</div>
						</li>
						<li data-transition="cube">
							<img src="{{ asset('assets/pic/slideshow/item-5.jpg') }}" alt="">
							<div class="tp-caption title skewfromrightshort tp-resizeme rs-parallaxlevel-0"
								data-x="center"
								data-hoffset="80"
								data-y="center"
								data-speed="500"
								data-start="500"
								data-easing="Power3.easeInOut"
								data-splitin="chars"
								data-splitout="none"
								data-elementdelay="0.1"
								data-endelementdelay="0.1"
								style="z-index: 1; max-width: auto; max-height: auto; white-space: nowrap;">Septiembre Descuento A Comerciales 
							</div>
							<div class="tp-caption sft tp-resizeme rs-parallaxlevel-0"
								data-x="center"
								data-hoffset="-215"
								data-y="center"
								data-voffset="-96"
								data-customin="x:0;y:0;z:0;rotationX:0;rotationY:0;rotationZ:0;scaleX:0;scaleY:0;skewX:0;skewY:0;opacity:0;transformPerspective:600;transformOrigin:50% 50%;"
								data-speed="500"
								data-start="3000"
								data-easing="Power3.easeInOut"
								data-splitin="none"
								data-splitout="none"
								data-elementdelay="0.1"
								data-endelementdelay="0.1"
								data-linktoslide="next"
								style="z-index: 1; max-width: auto; max-height: auto; white-space: nowrap;"><i class="fa fa-road"></i>
							</div>
							<div class="tp-caption sfl tp-resizeme rs-parallaxlevel-0"
								data-x="center"
								data-hoffset="-300"
								data-y="center"
								data-customin="x:0;y:0;z:0;rotationX:0;rotationY:0;rotationZ:0;scaleX:0;scaleY:0;skewX:0;skewY:0;opacity:0;transformPerspective:600;transformOrigin:50% 50%;"
								data-speed="500"
								data-start="3300"
								data-easing="Power3.easeInOut"
								data-splitin="none"
								data-splitout="none"
								data-elementdelay="0.1"
								data-endelementdelay="0.1"
								data-linktoslide="next"
								style="z-index: 1; max-width: auto; max-height: auto; white-space: nowrap;"><i class="fa fa-2 fa-users"></i>
							</div>
							<div class="tp-caption sfb tp-resizeme rs-parallaxlevel-0"
								data-x="center"
								data-hoffset="-215"
								data-y="center"
								data-voffset="96"
								data-customin="x:0;y:0;z:0;rotationX:0;rotationY:0;rotationZ:0;scaleX:0;scaleY:0;skewX:0;skewY:0;opacity:0;transformPerspective:600;transformOrigin:50% 50%;"
								data-speed="500"
								data-start="3600"
								data-easing="Power3.easeInOut"
								data-splitin="none"
								data-splitout="none"
								data-elementdelay="0.1"
								data-endelementdelay="0.1"
								data-linktoslide="next"
								style="z-index: 1; max-width: auto; max-height: auto; white-space: nowrap;"><i class="fa fa-3 fa-truck"></i>
							</div>
							<div class="tp-caption sfb tp-resizeme rs-parallaxlevel-0"
								data-x="center"
								data-hoffset="245"
								data-y="center" 
								data-voffset="91"
								data-customin="x:0;y:0;z:0;rotationX:0;rotationY:0;rotationZ:0;scaleX:0;scaleY:0;skewX:0;skewY:0;opacity:0;transformPerspective:600;transformOrigin:50% 50%;"
								data-speed="500"
								data-start="4000"
								data-easing="Power3.easeInOut"
								data-splitin="none"
								data-splitout="none"
								data-elementdelay="0.1"
								data-endelementdelay="0.1"
								data-linktoslide="next"
								style="z-index: 1; max-width: auto; max-height: auto; white-space: nowrap;"><a href="#" class="button-my">QUE HACEMOS?</a>
							</div>
						</li>
						<li data-transition="cube">
							<img src="{{ asset('assets/pic/slideshow/item-6.jpg') }}" alt="">
							<div class="tp-caption title skewfromrightshort tp-resizeme rs-parallaxlevel-0"
								data-x="center"
								data-hoffset="80"
								data-y="center" 
								data-speed="500"
								data-start="500"
								data-easing="Power3.easeInOut"
								data-splitin="chars"
								data-splitout="none"
								data-elementdelay="0.1"
								data-endelementdelay="0.1"
								style="z-index: 1; max-width: auto; max-height: auto; white-space: nowrap;">Realiza Tu Pago Anual Anticipado
							</div>
							<div class="tp-caption sft tp-resizeme rs-parallaxlevel-0"
								data-x="center"
								data-hoffset="-215"
								data-y="center"
								data-voffset="-96"
								data-customin="x:0;y:0;z:0;rotationX:0;rotationY:0;rotationZ:0;scaleX:0;scaleY:0;skewX:0;skewY:0;opacity:0;transformPerspective:600;transformOrigin:50% 50%;"
								data-speed="500"
								data-start="3000"
								data-easing="Power3.easeInOut"
								data-splitin="none"
								data-splitout="none"
								data-elementdelay="0.1"
								data-endelementdelay="0.1"
								data-linktoslide="next"
								style="z-index: 1; max-width: auto; max-height: auto; white-space: nowrap;"><i class="fa fa-file"></i>
							</div>
							<div class="tp-caption sfl tp-resizeme rs-parallaxlevel-0"
								data-x="center"
								data-hoffset="-300"
								data-y="center" 
								data-customin="x:0;y:0;z:0;rotationX:0;rotationY:0;rotationZ:0;scaleX:0;scaleY:0;skewX:0;skewY:0;opacity:0;transformPerspective:600;transformOrigin:50% 50%;"
								data-speed="500"
								data-start="3300"
								data-easing="Power3.easeInOut"
								data-splitin="none"
								data-splitout="none"
								data-elementdelay="0.1"
								data-endelementdelay="0.1"
								data-linktoslide="next"
								style="z-index: 1; max-width: auto; max-height: auto; white-space: nowrap;"><i class="fa fa-2 fa-recycle"></i>
							</div>
							<div class="tp-caption sfb tp-resizeme rs-parallaxlevel-0"
								data-x="center"
								data-hoffset="-215"
								data-y="center"
								data-voffset="96"
								data-customin="x:0;y:0;z:0;rotationX:0;rotationY:0;rotationZ:0;scaleX:0;scaleY:0;skewX:0;skewY:0;opacity:0;transformPerspective:600;transformOrigin:50% 50%;"
								data-speed="500"
								data-start="3600"
								data-easing="Power3.easeInOut"
								data-splitin="none"
								data-splitout="none"
								data-elementdelay="0.1"
								data-endelementdelay="0.1"
								data-linktoslide="next"
								style="z-index: 1; max-width: auto; max-height: auto; white-space: nowrap;"><i class="fa fa-3 fa-archive"></i>
							</div>
							<div class="tp-caption sfb tp-resizeme rs-parallaxlevel-0"
								data-x="center"
								data-hoffset="245"
								data-y="center" 
								data-voffset="91"
								data-customin="x:0;y:0;z:0;rotationX:0;rotationY:0;rotationZ:0;scaleX:0;scaleY:0;skewX:0;skewY:0;opacity:0;transformPerspective:600;transformOrigin:50% 50%;"
								data-speed="500"
								data-start="4000"
								data-easing="Power3.easeInOut"
								data-splitin="none"
								data-splitout="none"
								data-elementdelay="0.1"
								data-endelementdelay="0.1"
								data-linktoslide="next"
								style="z-index: 1; max-width: auto; max-height: auto; white-space: nowrap;"><a href="#" class="button-my">MÁS NOTICIAS</a>
							</div>
						</li>
					</ul>
				</div>
			</div>